packages:
  - web
  - mobile

packageExtensions:
  expo-audio@57.0.5:
    dependencies:
      expo-modules-core: ~57.0.18

minimumReleaseAgeExclude:
  - '@nestjs/cli@12.0.5'
  - '@nestjs/config@12.0.1'
  - dotenv@18.0.3
  - '@nestjs/common@12.1.0'
  - '@nestjs/core@12.1.0'
  - '@nestjs/platform-fastify@12.1.0'
  - expo-notifications@57.0.21
  - '@ap-education/federation@0.1.1-beta.0'
  - '@ap-education/shell-sdk@0.1.1-beta.0'
  - '@ap-education/ui@0.1.1-beta.0'

allowBuilds:
  esbuild: true
