export { Avatar, type AvatarProps } from './avatar/Avatar';
export { avatarColors, getAvatarColor } from './avatar/avatar-color';
export { Image, type ImageProps } from './avatar/Image';
export { resolveImageUrl } from './avatar/resolve-image-url';
export { useIsMobile } from './hooks/useIsMobile';
export { useMediaQuery } from './hooks/useMediaQuery';
export { SWIPE_SETTLE_TRANSITION, useTouchGesture } from './hooks/useTouchGesture';
export { MobileMenuButton } from './layout/MobileMenuButton';
export { type ShellHosts, useShellHosts } from './layout/shell-layout-context';
export { ShellLayout, type ShellLayoutProps } from './layout/ShellLayout';
export { RailAddTile, RailTile, type RailTileProps } from './rail/RailTile';
export { type RailApp } from './rail/types';
export { UserCard } from './user-card/UserCard';
