name: Web

on:
  push:
    branches: [main]
    paths:
      - 'web/**'
      - '*.json'
      - '*.yaml'
      - '*.mjs'
      - '.nvmrc'
      - '.prettier*'
      - '.github/workflows/web.yml'
  pull_request:
    paths:
      - 'web/**'
      - '*.json'
      - '*.yaml'
      - '*.mjs'
      - '.nvmrc'
      - '.prettier*'
      - '.github/workflows/web.yml'

permissions:
  contents: read

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          persist-credentials: false
      - uses: pnpm/setup@v3
        with:
          require-lockfile: true
          cache: true
      - run: pnpm lint:web
      - run: pnpm typecheck:web
      - run: pnpm test:web
      - run: pnpm build:web
      - run: pnpm exec prettier --check web
